services:
  - docker

before_install:
  - export PATH=$PATH:$HOME/.local/bin
  - docker-compose -f docker-compose.prod.yml up --build -d
  - docker ps -a

before_script:
  - sleep 5 #hacky sleep as we need to wait till the db container is up
  - docker-compose -f docker-compose.prod.yml exec db psql -U postgres -c "CREATE DATABASE \"mame-highscores-test\""
  - docker-compose -f docker-compose.prod.yml exec app node ./node_modules/typeorm/cli.js migration:run -c test
  - docker-compose -f docker-compose.prod.yml exec app npm install --only=dev


script:
  - docker-compose -f docker-compose.prod.yml exec app npm run test:e2e
  - docker-compose -f docker-compose.prod.yml exec app npm run test

before_deploy:
  - pip install --user awscli
  - eval $(aws ecr get-login --no-include-email --region ap-southeast-2)

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
