services:
  - docker
before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - docker-compose -f docker-compose.prod.yml up --build -d
  - docker ps -a
  - sleep 5
  - docker-compose -f docker-compose.prod.yml exec db psql -U postgres -c "CREATE DATABASE \"mame-highscores\""
script:
  - docker-compose exec app npm run test-model
after_success:
  - eval $(aws ecr get-login --no-include-email --region ap-southeast-2)
  - docker tag mame_highscores_app:latest 474801623431.dkr.ecr.ap-southeast-2.amazonaws.com/mame-highscores/app:latest
  - docker push 474801623431.dkr.ecr.ap-southeast-2.amazonaws.com/mame-highscores/app:latest