version: '3'

volumes:
  node_modules:
  frontend_node_modules:
  pgdata:
services:
  app:
    image: node:10.11.0
#    command: node app.js
    command: tail -f /dev/null
    working_dir: /home/node/app
    env_file:
      - development.env
    ports:
    - "3000:3000"
    - "4200:4200"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
      - frontend_node_modules:/home/node/app/frontend/node_modules
  db:
    image: postgres:10.7-alpine
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
    ports:
    - "5432:5432"
