version: '3'

volumes:
  pgdata:

services:
  app:
    image: mame_highscores_app:latest
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /home/node/app
    #command: tail -f /dev/null
    command: node app.js
    environment:
      NODE_ENV: production

  db:
    image: postgres:10.5-alpine
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: