version: '3'

volumes:
  pgdata:

services:
  app:
    image: mame_highscores_app:latest
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /home/node/app
    command: tail -f /dev/null
    #    command: npm run start:prod
#    command: node dist/main.js
    environment:
      NODE_ENV: production
#      TYPEORM_CONNECTION: postgres
#      TYPEORM_HOST: db
#      TYPEORM_PORT: 5432
#      TYPEORM_USERNAME: postgres
#      TYPEORM_PASSWORD: example
#      TYPEORM_DATABASE: mame-highscores-test
#      TYPEORM_SYNCHRONIZE: 'false'
#      TYPEORM_DROP_SCHEMA: 'false'
#      TYPEORM_LOGGING: all
#      TYPEORM_ENTITIES: '/home/node/app/dist/entity/*.entity.js'
#      TYPEORM_ENTITIES_DIR: dist/src/entity
    ports:
      - "3000:3000"

  db:
    image: postgres:10.7-alpine
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
    ports:
        - "5432:5432"