version: '3'

volumes:
  pgdata:

services:
  app:
    image: mame_highscores_app:latest
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /home/node/app
    command: tail -f /dev/null
    #    command: npm run start:prod
#    command: node dist/main.js
    environment:
      NODE_ENV: test
  db:
    image: postgres:10.7-alpine
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
