version: '3'

volumes:
  pgdata:

services:
  app:
    image: 474801623431.dkr.ecr.ap-southeast-2.amazonaws.com/mame-highscores/app:latest
    working_dir: /home/node/app
    restart: always
    command: node dist/main.js
    env_file:
      - app.env
    environment:
      NODE_ENV: production
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-southeast-2
        awslogs-group: arcadehiscores
        awslogs-stream: app
  db:
    image: postgres:10.7-alpine
    restart: always
    volumes:
    - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-southeast-2
        awslogs-group: arcadehiscores
        awslogs-stream: db