var assert = require('assert');

describe('EmailService', function () {

  //this.timeout(5000);

  describe('#sendBeatenEmail()', function () {

    it('should send an email', function (done) {


      var game = { id: 1234, full_name: 'Test game', scores: [{ id: 2, score: '234', name: 'FOO'}]};
      var beatenBy = {
        id: 3, score: '345', name: 'XYZ',
        user: { id: 2, username: 'Test2', email: 'invalid2'}
      };

      var beaten = { id: 2, score: '234', name: 'FOO',
        user: { id: 1, username: 'Test1', email: 'invalid1'} };

      EmailService.sendBeatenEmail(game, beatenBy, beaten, { to: 'mamehighscores@gmail.com' }, function (err, info) {
        assert.equal(err, null, 'Error sending email');

        var emailAsString = info.response.toString(); //this should be the email generated by the node-mailer stub

        //simple test to see if the game name is somewhere in the email
        assert.ok(emailAsString.indexOf(game.full_name) > -1, "Game name not found in email");

        //console.log(emailAsString);

        done();
      });

    });
  });
});