
var assert = require('assert');

describe('EmailService', function () {

  //this.timeout(5000);

  describe('#sendBeatenEmail()', function () {

    it('should send an email', function (done) {


      var beatenEmailData = {
        game: { id: 1234, full_name: 'Test game'},
        beaten: {
          id: 2, score: '234', name: 'FOO',
          user: { id: 1, username: 'Test1', email: 'invalid1'}
        },
        beatenBy: {
          id: 3, score: '345', name: 'XYZ',
          user: { id: 2, username: 'Test2', email: 'invalid2'}
        }
      };


      EmailService.sendBeatenEmail(beatenEmailData, {to: 'mamehighscores@gmail.com', subject: 'email service test'}, function(err, info){
        assert.equal(err, null, 'Error sending email');

        var emailAsString = info.response.toString(); //this should be the email generated by the node-mailer stub

        //simple test to see if the game name is somewhere in the email
        assert.ok(emailAsString.indexOf(beatenEmailData.game.full_name) > -1, "Game name not found in email");

        done();
      });

    });
  });
});